### ISSUE TITLE
Further issue with PubMed XML

### ISSUE THREAD

**Issue by cameronneylon** [ananelson/oacensus#6]
In some cases the month element in the PubDate entry is not a number and appears to be a three month name:

```
Camerons-MacBook-Air:uwe Cameron2$ oacensus run --config example1.yaml --reports excel
    removing old db file oacensus.sqlite3
running pubmed
.oacensus/cache/8efbbedc16579aba282ffd5a07b5d7e8
  calling scrape method...
  there are 2558 total articles matching the search
  calling process method...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/oacensus", line 9, in <module>
    load_entry_point('oacensus==0.0.1', 'console_scripts', 'oacensus')()
  File "/Users/Cameron2/Documents/Python/plos/oacensus/oacensus/commands.py", line 26, in run
    args.parse_and_run_command(sys.argv[1:], mod, default_command=default_cmd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/modargs/args.py", line 381, in parse_and_run_command
    command_module(mod, command, options, cli_options=cli_options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/modargs/args.py", line 286, in command_module
    function(**options)
  File "/Users/Cameron2/Documents/Python/plos/oacensus/oacensus/commands.py", line 147, in run_command
    scraper.run()
  File "/Users/Cameron2/Documents/Python/plos/oacensus/oacensus/scraper.py", line 61, in run
    self.process()
  File "/Users/Cameron2/Documents/Python/plos/oacensus/oacensus/scrapers/pubmed.py", line 185, in process
    date_published = self.parse_date(article_entry.find("ArticleDate"))
  File "/Users/Cameron2/Documents/Python/plos/oacensus/oacensus/scrapers/pubmed.py", line 122, in parse_date
    int(entry.findtext('Month')),
ValueError: invalid literal for int() with base 10: 'Feb'
```

**Comment by ananelson** [comment]
What was the search query which resulted in these dates? (so I can test)

**Comment by cameronneylon** [comment]
Oops, sorry. The search was "Cambridge University[Affiliation]"

**Comment by ananelson** [comment]
If there's no day in the date, just month and year, what day should we default to?

**Comment by ananelson** [comment]
Have defaulted to "1" if either month or day is missing, and no date if year is missing. Have also changed to reference Journal's PubDate which is more widespread. Am closing this, please reopen if further work is needed.
